//! The `KronAlert` type — a fired security detection.
//!
//! A `KronAlert` is produced by the stream processor when a detection fires.
//! It aggregates multiple related events into a single, deduplicated alert
//! that is written to `ClickHouse` and dispatched for notification.
//!
//! Alerts are deduplicated within 15-minute windows: multiple events matching
//! the same rule on the same asset produce one `KronAlert`, not many.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::enums::{AlertStatus, DetectionSource, Severity};
use crate::ids::{AlertId, RuleId, TenantId};

/// A security alert generated by the KRON detection engine.
///
/// Maps 1:1 to a row in the `alerts` ClickHouse/DuckDB table.
/// See `docs/Database.md` for the full schema.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(clippy::struct_excessive_bools)]
pub struct KronAlert {
    // --- Identity ---
    /// Unique alert identifier.
    pub alert_id: AlertId,
    /// The tenant this alert belongs to. Mandatory on every alert.
    pub tenant_id: TenantId,

    // --- Detection ---
    /// The rule that triggered this alert.
    pub rule_id: RuleId,
    /// Human-readable rule name (snapshot at alert creation time).
    pub rule_name: String,
    /// Rule version at detection time.
    pub rule_version: Option<String>,
    /// Which detection subsystem produced this alert.
    pub detection_source: DetectionSource,

    // --- Timing ---
    /// When this alert record was created in KRON.
    pub created_at: DateTime<Utc>,
    /// Timestamp of the first matching event in the dedup window.
    pub first_seen: DateTime<Utc>,
    /// Timestamp of the most recent matching event.
    pub last_seen: DateTime<Utc>,
    /// Number of events grouped into this alert within the dedup window.
    pub event_count: u32,

    // --- Risk ---
    /// Composite risk score 0–100 (≥80 Critical, ≥60 High, ≥40 Medium, ≥20 Low).
    pub risk_score: u8,
    /// Qualitative severity derived from `risk_score`.
    pub severity: Severity,
    /// Model confidence that this is a true positive (0.0–1.0).
    pub confidence: Option<f32>,

    // --- MITRE ATT&CK ---
    /// MITRE tactic name (e.g. "Lateral Movement").
    pub mitre_tactic: Option<String>,
    /// MITRE technique ID (e.g. "T1021").
    pub mitre_technique: Option<String>,
    /// MITRE sub-technique ID (e.g. "T1021.001").
    pub mitre_sub_tech: Option<String>,
    /// Lockheed Martin kill chain stage.
    pub kill_chain_stage: Option<String>,

    // --- Affected entities ---
    /// Hostnames or asset IDs affected by this alert.
    pub affected_assets: Vec<String>,
    /// Usernames of accounts involved in this alert.
    pub affected_users: Vec<String>,
    /// IPv4 addresses involved in this alert (stored as strings for portability).
    pub affected_ips: Vec<String>,

    // --- Evidence ---
    /// UUIDs of the `events` rows that triggered this alert.
    pub evidence_event_ids: Vec<Uuid>,
    /// JSON-serialized matched field values for triage context.
    pub raw_matches: Option<String>,

    // --- AI enrichment (populated by kron-ai in Phase 2+) ---
    /// Plain English narrative summary of the alert.
    pub narrative_en: Option<String>,
    /// Hindi narrative summary.
    pub narrative_hi: Option<String>,
    /// Tamil narrative summary.
    pub narrative_ta: Option<String>,
    /// Telugu narrative summary.
    pub narrative_te: Option<String>,
    /// JSON array of causal event chain for root cause analysis.
    pub root_cause_chain: Option<String>,
    /// Estimated probability this is a false positive (0.0–1.0).
    pub fp_probability: Option<f32>,
    /// Suggested SOAR playbook ID to run in response.
    pub suggested_playbook: Option<String>,

    // --- Lifecycle ---
    /// Current alert status.
    pub status: AlertStatus,
    /// User ID assigned to investigate this alert.
    pub assigned_to: Option<String>,
    /// When the alert was resolved.
    pub resolved_at: Option<DateTime<Utc>>,
    /// User ID who resolved the alert.
    pub resolved_by: Option<String>,
    /// Analyst notes from the resolution.
    pub resolution_notes: Option<String>,
    /// Optional case ID linking multiple related alerts.
    pub case_id: Option<Uuid>,

    // --- Compliance ---
    /// CERT-In incident category (if applicable to this alert type).
    pub cert_in_category: Option<String>,
    /// RBI IS audit control reference.
    pub rbi_control: Option<String>,
    /// Whether this alert is subject to DPDP Act reporting requirements.
    pub dpdp_applicable: bool,

    // --- Notifications ---
    /// Whether a `WhatsApp` notification was sent for this alert.
    pub whatsapp_sent: bool,
    /// Whether an SMS notification was sent.
    pub sms_sent: bool,
    /// Whether an email notification was sent.
    pub email_sent: bool,
    /// Timestamp of the last notification sent for this alert.
    pub notification_ts: Option<DateTime<Utc>>,

    /// Schema version for forward compatibility.
    pub schema_version: u8,
}

impl KronAlert {
    /// Returns `true` if this alert requires immediate notification (Critical or High severity).
    #[must_use]
    pub fn is_immediate(&self) -> bool {
        self.severity.is_immediate()
    }

    /// Returns `true` if no notification has been sent yet for this alert.
    #[must_use]
    pub fn needs_notification(&self) -> bool {
        !self.whatsapp_sent && !self.sms_sent && !self.email_sent
    }

    /// Returns `true` if the alert is still active (not resolved, false-positive, or suppressed).
    #[must_use]
    pub fn is_active(&self) -> bool {
        !matches!(
            self.status,
            AlertStatus::Resolved | AlertStatus::FalsePositive | AlertStatus::Suppressed
        )
    }

    /// Returns `true` if the alert has been assigned to an analyst.
    #[must_use]
    pub fn is_assigned(&self) -> bool {
        self.assigned_to.is_some()
    }
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;

    fn make_alert(severity: Severity) -> KronAlert {
        KronAlert {
            alert_id: AlertId::new(),
            tenant_id: TenantId::new(),
            rule_id: RuleId::new(),
            rule_name: "Test Rule".to_string(),
            rule_version: None,
            detection_source: DetectionSource::Sigma,
            created_at: Utc::now(),
            first_seen: Utc::now(),
            last_seen: Utc::now(),
            event_count: 1,
            risk_score: severity.score_threshold(),
            severity,
            confidence: None,
            mitre_tactic: None,
            mitre_technique: None,
            mitre_sub_tech: None,
            kill_chain_stage: None,
            affected_assets: vec![],
            affected_users: vec![],
            affected_ips: vec![],
            evidence_event_ids: vec![],
            raw_matches: None,
            narrative_en: None,
            narrative_hi: None,
            narrative_ta: None,
            narrative_te: None,
            root_cause_chain: None,
            fp_probability: None,
            suggested_playbook: None,
            status: AlertStatus::Open,
            assigned_to: None,
            resolved_at: None,
            resolved_by: None,
            resolution_notes: None,
            case_id: None,
            cert_in_category: None,
            rbi_control: None,
            dpdp_applicable: false,
            whatsapp_sent: false,
            sms_sent: false,
            email_sent: false,
            notification_ts: None,
            schema_version: 1,
        }
    }

    #[test]
    fn test_critical_alert_when_checked_then_is_immediate() {
        assert!(make_alert(Severity::Critical).is_immediate());
    }

    #[test]
    fn test_high_alert_when_checked_then_is_immediate() {
        assert!(make_alert(Severity::High).is_immediate());
    }

    #[test]
    fn test_medium_alert_when_checked_then_is_not_immediate() {
        assert!(!make_alert(Severity::Medium).is_immediate());
    }

    #[test]
    fn test_new_alert_when_checked_then_needs_notification() {
        assert!(make_alert(Severity::High).needs_notification());
    }

    #[test]
    fn test_whatsapp_sent_alert_when_checked_then_does_not_need_notification() {
        let mut alert = make_alert(Severity::High);
        alert.whatsapp_sent = true;
        assert!(!alert.needs_notification());
    }

    #[test]
    fn test_open_alert_when_checked_then_is_active() {
        assert!(make_alert(Severity::High).is_active());
    }

    #[test]
    fn test_resolved_alert_when_checked_then_is_not_active() {
        let mut alert = make_alert(Severity::High);
        alert.status = AlertStatus::Resolved;
        assert!(!alert.is_active());
    }

    #[test]
    fn test_false_positive_alert_when_checked_then_is_not_active() {
        let mut alert = make_alert(Severity::High);
        alert.status = AlertStatus::FalsePositive;
        assert!(!alert.is_active());
    }

    #[test]
    fn test_alert_when_serialized_then_round_trips_through_json() {
        let alert = make_alert(Severity::Critical);
        let json = serde_json::to_string(&alert).expect("must serialize");
        let back: KronAlert = serde_json::from_str(&json).expect("must deserialize");
        assert_eq!(alert.alert_id, back.alert_id);
        assert_eq!(alert.tenant_id, back.tenant_id);
    }
}
