import UIKit
import Flutter
import Firebase
import UserNotifications

/// KRON SIEM iOS app delegate.
///
/// Responsibilities:
/// - Bootstrap Firebase on first launch
/// - Register for push notifications (APNs → FCM)
/// - Configure notification presentation for foreground P1/P2 alerts
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {

    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        // Configure Firebase before GeneratedPluginRegistrant so firebase_messaging
        // can register its method channel with the correct FirebaseApp instance.
        FirebaseApp.configure()

        // Register Flutter plugins (auto-generated by flutter pub get).
        GeneratedPluginRegistrant.register(with: self)

        // Request push notification permission on first launch.
        // The firebase_messaging plugin will present the system prompt;
        // we configure the delegate so foreground notifications are shown.
        UNUserNotificationCenter.current().delegate = self

        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }

    // MARK: - APNs token forwarding

    override func application(
        _ application: UIApplication,
        didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data
    ) {
        // Forward APNs token to Firebase Messaging so FCM can send push notifications.
        super.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
    }

    override func application(
        _ application: UIApplication,
        didFailToRegisterForRemoteNotificationsWithError error: Error
    ) {
        // Log but do not crash — the app functions without push notifications.
        print("[KRON] Failed to register for remote notifications: \(error.localizedDescription)")
    }

    // MARK: - Foreground notification presentation

    /// Show P1/P2 alerts as banners even when the app is in the foreground.
    override func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        willPresent notification: UNNotification,
        withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void
    ) {
        let category = notification.request.content.categoryIdentifier
        let options: UNNotificationPresentationOptions
        if category == "kron_p1_alerts" || category == "kron_soar" {
            // Always show critical alert banners + play sound.
            options = [.banner, .sound, .badge]
        } else {
            // Informational alerts: show badge only when app is foreground.
            options = [.badge]
        }
        completionHandler(options)
    }
}
