//
//  GeneratedPluginRegistrant.h
//
//  This file is auto-generated by `flutter pub get`.
//  It is committed so Xcode can resolve the import at project open time,
//  but will be overwritten by the Flutter tooling before every build.
//

#ifndef GeneratedPluginRegistrant_h
#define GeneratedPluginRegistrant_h

#import <Flutter/Flutter.h>

@interface GeneratedPluginRegistrant : NSObject

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry;

@end

#endif /* GeneratedPluginRegistrant_h */
