//
//  GeneratedPluginRegistrant.m
//
//  This file is auto-generated by `flutter pub get`.
//  Committed as a placeholder; overwritten by flutter tooling before every build.
//  DO NOT EDIT — your changes will be overwritten.
//

#import "GeneratedPluginRegistrant.h"

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  // Plugin registrations are injected here by flutter pub get.
}

@end
