/* vmlinux.h — minimal BTF-derived kernel type definitions for CO-RE eBPF.
 *
 * In a real build this file is generated per-kernel via:
 *   bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
 *
 * This stub contains only the subset of types needed by the three KRON eBPF
 * programs. It is sufficient for clang CO-RE compilation targeting any kernel
 * 5.4+ that exposes the same stable ABI fields.
 *
 * DO NOT edit this file manually. Re-generate from a target kernel when
 * upgrading or adding new tracepoints/kprobes.
 */
#pragma once

/* Prevent standard headers from conflicting with BTF-derived types. */
#define __VMLINUX_H__

typedef unsigned char      __u8;
typedef unsigned short     __u16;
typedef unsigned int       __u32;
typedef unsigned long long __u64;
typedef signed char        __s8;
typedef signed short       __s16;
typedef signed int         __s32;
typedef signed long long   __s64;
typedef __u64              __be64;
typedef __u32              __be32;
typedef __u16              __be16;

/* ── task_struct (CO-RE fields only) ─────────────────────────────────── */

struct task_struct {
    volatile long state;
    __u32 pid;
    __u32 tgid;
    char comm[16];
    struct task_struct *parent;
    /* … other fields omitted; access via BPF CO-RE helpers only … */
} __attribute__((preserve_access_index));

/* ── socket / inet_sock (CO-RE fields only) ──────────────────────────── */

struct sock_common {
    union {
        struct {
            __be32 skc_daddr;
            __be32 skc_rcv_saddr;
        };
    };
    __u16 skc_dport;
    __u16 skc_num;
} __attribute__((preserve_access_index));

struct sock {
    struct sock_common __sk_common;
} __attribute__((preserve_access_index));

/* ── tracepoint context structs ──────────────────────────────────────── */

struct trace_event_raw_sys_enter {
    unsigned long long unused;
    long id;
    unsigned long args[6];
};

struct trace_event_raw_sys_exit {
    unsigned long long unused;
    long id;
    long ret;
};
